//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectScan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectScan.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Kinect....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting aborted..
        /// </summary>
        internal static string ConnectingAborted {
            get {
                return ResourceManager.GetString("ConnectingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established..
        /// </summary>
        internal static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating GPU processing pipeline....
        /// </summary>
        internal static string CreatingGPUProcessingPipeline {
            get {
                return ResourceManager.GetString("CreatingGPUProcessingPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories cannot be created!.
        /// </summary>
        internal static string DirectoryCreationError {
            get {
                return ResourceManager.GetString("DirectoryCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported models.
        /// </summary>
        internal static string ExportedModels {
            get {
                return ResourceManager.GetString("ExportedModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide advanced settings.
        /// </summary>
        internal static string HideAdvancedSettings {
            get {
                return ResourceManager.GetString("HideAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide test settings.
        /// </summary>
        internal static string HideTestSettings {
            get {
                return ResourceManager.GetString("HideTestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This label is already used. Overwrite existing files?.
        /// </summary>
        internal static string LabelNameConflict {
            get {
                return ResourceManager.GetString("LabelNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A label must be selected..
        /// </summary>
        internal static string LabelSpecificationNeeded {
            get {
                return ResourceManager.GetString("LabelSpecificationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading model....
        /// </summary>
        internal static string LoadingModel {
            get {
                return ResourceManager.GetString("LoadingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model loaded..
        /// </summary>
        internal static string ModelLoaded {
            get {
                return ResourceManager.GetString("ModelLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model loading failed..
        /// </summary>
        internal static string ModelLoadingFailed {
            get {
                return ResourceManager.GetString("ModelLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} mode is not supported by this device..
        /// </summary>
        internal static string ModeUnsupported {
            get {
                return ResourceManager.GetString("ModeUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening video stream....
        /// </summary>
        internal static string OpeningVideoStream {
            get {
                return ResourceManager.GetString("OpeningVideoStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model.
        /// </summary>
        internal static string OpenModel {
            get {
                return ResourceManager.GetString("OpenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  position(s) have been captured so far..
        /// </summary>
        internal static string PositionCaptured {
            get {
                return ResourceManager.GetString("PositionCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare to shutdown....
        /// </summary>
        internal static string PrepareToShutdown {
            get {
                return ResourceManager.GetString("PrepareToShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add probe: Click on the image to add probe..
        /// </summary>
        internal static string ProbeAddHelp {
            get {
                return ResourceManager.GetString("ProbeAddHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add multiple position probes here..
        /// </summary>
        internal static string ProbeHelp {
            get {
                return ResourceManager.GetString("ProbeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move probe: Select the new position..
        /// </summary>
        internal static string ProbeMoveEndHelp {
            get {
                return ResourceManager.GetString("ProbeMoveEndHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move probe: Select the probe on the image..
        /// </summary>
        internal static string ProbeMoveStartHelp {
            get {
                return ResourceManager.GetString("ProbeMoveStartHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove probe: Select the probe on the image..
        /// </summary>
        internal static string ProbeRemoveHelp {
            get {
                return ResourceManager.GetString("ProbeRemoveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing halted..
        /// </summary>
        internal static string ProcessingHalted {
            get {
                return ResourceManager.GetString("ProcessingHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing resumed.
        /// </summary>
        internal static string ProcessingResumed {
            get {
                return ResourceManager.GetString("ProcessingResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing started..
        /// </summary>
        internal static string ProcessingStarted {
            get {
                return ResourceManager.GetString("ProcessingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing stopped..
        /// </summary>
        internal static string ProcessingStopped {
            get {
                return ResourceManager.GetString("ProcessingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreating GPU processing pipeline....
        /// </summary>
        internal static string RecreatingGPUProcessingPipeline {
            get {
                return ResourceManager.GetString("RecreatingGPUProcessingPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releasing GPU processing pipeline....
        /// </summary>
        internal static string ReleasingGPUProcessingPipeline {
            get {
                return ResourceManager.GetString("ReleasingGPUProcessingPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of &quot;{0}&quot; complete..
        /// </summary>
        internal static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving &quot;{0}&quot;, with the error message: {1}..
        /// </summary>
        internal static string SaveUnsuccessful {
            get {
                return ResourceManager.GetString("SaveUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select calibration folder.
        /// </summary>
        internal static string SelectCalibrationFolder {
            get {
                return ResourceManager.GetString("SelectCalibrationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the working directory:.
        /// </summary>
        internal static string SelectWorkingDirectory {
            get {
                return ResourceManager.GetString("SelectWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show advanced settings.
        /// </summary>
        internal static string ShowAdvancedSettings {
            get {
                return ResourceManager.GetString("ShowAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show test settings.
        /// </summary>
        internal static string ShowTestSettings {
            get {
                return ResourceManager.GetString("ShowTestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
